repository:
  - .github/**
  - .gitignore
  - .gitattributes
  - README.md
  - SECURITY.md
  - LICENSE
  - utils/**

dependencies:
  - package.json
  - package-lock.json

map revision:
  - maps/**/map.json
  - maps/**/map.tmx
  - maps/**/locations.json

lang revision:
  - client/lang/**

sprite revision:
  - maps/**/textures.json
  - maps/**/textures.png
  - maps/**/textures.tps
  - maps/**/tileset.textures.json
  - maps/**/tileset.textures.png
  - maps/**/tileset.textures.raw.png

server side code:
  - server/**

client side code:
  - client/**