name: "Build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm clean-install
    - run: npm test
      env:
        CI: true
    - run: npm run diff-map-overworld -- --token=${{ secrets.BOT_TOKEN }} --event=${{ github.event_path }} --owner=${{ github.actor }}

  codeql:
    name: CodeQL
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
    - uses: github/codeql-action/init@v1
      with:
        languages: javascript
    - uses: github/codeql-action/analyze@v1
